version: "3.8"

services:

  backend:
    build:
      context: ./backend/
      dockerfile: DockerFile
    image: backend
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - database
    env_file:
      - ./backend/.env.local

  cache:
    image: redis:7.4.2-alpine
    container_name: cache
    ports:
      - "6379:6379"

  database:
    image: mysql:8.3.0
    restart: always
    container_name: database
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - ./backend/.env.local

  adminer:
    image: adminer:5.1.0
    container_name: adminer
    ports:
      - '8000:8080'
    depends_on:
      - database
    environment:
      - ADMINER_DEFAULT_SERVER=database

volumes:
  data:
